imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    appointments_page_length: 100
    ch_database_date: April 20th 2011
    search_page_length: 20
        

framework:
    secret:        %secret%
    router:        
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_parameters: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator: { fallback: en }
    default_locale:   %locale%
    session:
        # storage_id: session.storage.native
        # handler_id: session.handler.native_file
        # cookie_lifetime:   3600
        # cookie_path:       \
        # cookie_domain:     example.com
        # cookie_secure:     true
        # cookie_httponly:   true
    trust_proxy_headers: false
    

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    bundles: []
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        port:     %database_port%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    spool: { type: memory }
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%


services:
    search:
        class: SphinxClient
        calls:
            - [setArrayResult, [true]]
            - [setLimits, [0, %search_page_length%, 1000]]

    directorsearch:
        class: Tui\DirectorsBundle\Extension\DirectorSearchExtension
        arguments: [@search, @database_connection, @router, @doctrine]
        calls:
            - [setPageLength, [%search_page_length%]]

    Age.twig.extension:
        class: Tui\DirectorsBundle\Extension\AgeExtension
        tags:
            - { name: twig.extension }

    text.twig.extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
