imports:
    - { resource: config_dev.yml }

framework:
    error_handler: false
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false
