imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

parameters:
    appointments_page_length: 100
    ch_database_date: March 4th 2010
    search_page_length: 20
        

framework:
    secret:        %secret%
    charset:       UTF-8
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator: { fallback: en }
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    extensions:       [twig.extension.text]

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false


services:
    search:
        class: SphinxClient
        calls:
            - [setArrayResult, [true]]
            - [setLimits, [0, %search_page_length%, 1000]]


fos_user:
    db_driver:     orm
    firewall_name: main
    class:
        model:
            user:  Tui\DirectorsBundle\Entity\User

