directors:
    resource: "@TuiDirectorsBundle/Controller/DefaultController.php"
    type:     annotation

appointees:
    resource: "@TuiDirectorsBundle/Controller/AppointeeController.php"
    type:   annotation
    
companies:
    resource: "@TuiDirectorsBundle/Controller/CompanyController.php"
    type:   annotation