directors:
    resource: "@TuiDirectorsBundle/Controller/DefaultController.php"
    type:     annotation

appointees:
    resource: "@TuiDirectorsBundle/Controller/AppointeeController.php"
    type:   annotation
    
companies:
    resource: "@TuiDirectorsBundle/Controller/CompanyController.php"
    type:   annotation


# fos_user_security:
#     resource: "@FOSUserBundle/Resources/config/routing/security.xml"
# 
# fos_user_user:
#     resource: "@FOSUserBundle/Resources/config/routing/user.xml"
#     prefix: /user
# 
